# Generated by Django 1.11.11 on 2018-06-10 11:02
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bootstrap4_carousel', '0002_bootstrap4carousel_carousel_aspect_ratio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bootstrap4carousel',
            old_name='carousel_style',
            new_name='template',
        ),
    ]
