# Generated by Django 2.2.16 on 2022-01-18 16:14

from django.db import migrations, models

from ..constants import GRID_CONTAINER_CHOICES


class Migration(migrations.Migration):

    dependencies = [
        ('bootstrap4_grid', '0004_remove_bootstrap4gridcolumn_column_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bootstrap4gridcontainer',
            name='container_type',
            field=models.CharField(choices=GRID_CONTAINER_CHOICES, default=GRID_CONTAINER_CHOICES[0][1][0][0], help_text='Defines if the grid should use fixed width (<code>.container</code>) or fluid width (<code>.container-fluid</code>).', max_length=255, verbose_name='Container type'),
        ),
    ]
