# Generated by Django 2.2.13 on 2020-06-10 11:28

from django.db import migrations
import djangocms_bootstrap4.contrib.bootstrap4_grid.models
import enumfields.fields
import settings


class Migration(migrations.Migration):

    dependencies = [
        ('bootstrap4_grid', '0006_add_fields_background_and_spacing'),
    ]

    operations = [
        migrations.AddField(
            model_name='bootstrap4gridcontainer',
            name='spacing_vertical_type',
            field=enumfields.fields.EnumField(default='margin', enum=djangocms_bootstrap4.contrib.bootstrap4_grid.models.SpacingVerticalType, max_length=255, verbose_name='Vertical spacing type'),
        ),
        migrations.AlterField(
            model_name='bootstrap4gridcontainer',
            name='background',
            field=enumfields.fields.EnumField(default='background-none', enum=settings.GridContainerBackground, max_length=255, verbose_name='Background'),
        ),
        migrations.AlterField(
            model_name='bootstrap4gridcontainer',
            name='container_type',
            field=enumfields.fields.EnumField(default='container', enum=settings.GridContainerType, max_length=255, verbose_name='Container width'),
        ),
        migrations.AlterField(
            model_name='bootstrap4gridcontainer',
            name='spacing',
            field=enumfields.fields.EnumField(default='spacing-none', enum=settings.GridContainerSpacing, max_length=255, verbose_name='Vertical spacing'),
        ),
    ]
