# Generated by Django 2.2.13 on 2020-06-10 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bootstrap4_grid', '0007_add_field_spacing_vertical_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bootstrap4gridcontainer',
            old_name='spacing',
            new_name='spacing_vertical',
        ),
    ]
