# Generated by Django 2.2.13 on 2020-06-15 18:29

from django.db import migrations
import djangocms_bootstrap4.contrib.bootstrap4_grid.constants
import djangocms_bootstrap4.contrib.bootstrap4_grid.models
import enumfields.fields
import settings


class Migration(migrations.Migration):
    dependencies = [
        ('bootstrap4_grid', '0011_drop_field_spacing_horizontal'),
    ]

    operations = [
        migrations.AddField(
            model_name='bootstrap4gridcontainer',
            name='width_internal',
            field=enumfields.fields.EnumField(
                default='full-width',
                enum=djangocms_bootstrap4.contrib.bootstrap4_grid.constants.GridContainerWidthInternal,
                help_text='You can change it eg if you want to have a full-width gray background, but a limited content width within that background',
                max_length=255,
                verbose_name='Internal width',
            ),
        ),
        migrations.AlterField(
            model_name='bootstrap4gridcontainer',
            name='container_type',
            field=enumfields.fields.EnumField(
                default='container',
                enum=djangocms_bootstrap4.contrib.bootstrap4_grid.constants.GridContainerType,
                max_length=255,
                verbose_name='External width',
            ),
        ),
    ]
