# Generated by Django 2.2.14 on 2020-08-02 09:11

from django.db import migrations, models
import djangocms_bootstrap4.contrib.bootstrap4_grid.models
import enumfields.fields
import djangocms_bootstrap4.contrib.bootstrap4_grid.constants


class Migration(migrations.Migration):

    dependencies = [
        ('bootstrap4_grid', '0013_alter_field_container_type_with_new_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='bootstrap4gridcolumn',
            name='horizontal_alignment',
            field=models.CharField(choices=[('align-items-start', 'Align items start'), ('align-items-center', 'Align items center'), ('align-items-end', 'Align items end'), ('align-items-stretch', 'Align items stretch')], default='align-items-start', help_text='Read more in the <a href="https://getbootstrap.com/docs/4.0/layout/grid/#horizontal-alignment" target="_blank">documentation</a>.', max_length=255, verbose_name='Horizontal alignment'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bootstrap4gridcontainer',
            name='spacing_vertical',
            field=enumfields.fields.EnumField(default='none', enum=djangocms_bootstrap4.contrib.bootstrap4_grid.constants.GridContainerSpacing, max_length=255, verbose_name='Vertical spacing'),
        ),
        migrations.AlterField(
            model_name='bootstrap4gridcontainer',
            name='width_internal',
            field=enumfields.fields.EnumField(default='full-width', enum=djangocms_bootstrap4.contrib.bootstrap4_grid.constants.GridContainerWidthInternal, max_length=255, verbose_name='Internal content width'),
        ),
        migrations.AlterField(
            model_name='bootstrap4gridrow',
            name='gutters_vertical',
            field=enumfields.fields.EnumField(default='none', enum=djangocms_bootstrap4.contrib.bootstrap4_grid.models.GuttersVertical, help_text='Vertical spacing between the columns inside', max_length=32),
        ),
    ]
