# Generated by Django 2.2.14 on 2020-08-02 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bootstrap4_grid', '0014_add_field_horizontal_alignment_to_column'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bootstrap4gridcolumn',
            name='column_alignment',
            field=models.CharField(blank=True, choices=[('align-self-start', 'Align self start'), ('align-self-center', 'Align self center'), ('align-self-end', 'Align self end')], max_length=255, verbose_name='Vertical alignment'),
        ),
        migrations.AlterField(
            model_name='bootstrap4gridcolumn',
            name='horizontal_alignment',
            field=models.CharField(choices=[('align-items-start', 'Align items start'), ('align-items-center', 'Align items center'), ('align-items-end', 'Align items end'), ('align-items-stretch', 'Align items stretch')], max_length=255, verbose_name='Horizontal alignment'),
        ),
    ]
