# Generated by Django 3.1.4 on 2021-01-20 20:58

from django.db import migrations
import djangocms_bootstrap4.contrib.bootstrap4_grid.constants
import enumfields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('bootstrap4_grid', '0015_alter_metadata'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bootstrap4gridcontainer',
            old_name='spacing_vertical',
            new_name='spacing_vertical_external',
        ),
        migrations.RenameField(
            model_name='bootstrap4gridcontainer',
            old_name='width_internal',
            new_name='width',
        ),
    ]
