# Generated by Django 3.1.4 on 2021-07-19 18:34

import backend.settings
from django.db import migrations, models
import enumfields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('bootstrap4_grid', '0017_add_fields_for_spacing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bootstrap4gridcolumn',
            name='horizontal_alignment',
            field=models.CharField(choices=[('align-items-start', 'Align items start'), ('align-items-center', 'Align items center'), ('align-items-end', 'Align items end'), ('align-items-stretch', 'Align items stretch')], default='align-items-start', max_length=255, verbose_name='Horizontal alignment'),
        ),
        migrations.AlterField(
            model_name='bootstrap4gridcontainer',
            name='background',
            field=enumfields.fields.EnumField(default='background-none', enum=backend.settings.GridContainerBackground, max_length=255, verbose_name='Background'),
        ),
        migrations.AlterField(
            model_name='bootstrap4gridcontainer',
            name='container_type',
            field=enumfields.fields.EnumField(default='container-fluid', enum=backend.settings.GridContainerType, max_length=255, verbose_name='External width'),
        ),
        migrations.AlterField(
            model_name='bootstrap4gridcontainer',
            name='spacing_vertical_external',
            field=enumfields.fields.EnumField(default='spacing-none', enum=backend.settings.GridContainerSpacing, max_length=255, verbose_name='Vertical external spacing'),
        ),
        migrations.AlterField(
            model_name='bootstrap4gridcontainer',
            name='spacing_vertical_internal',
            field=enumfields.fields.EnumField(default='none', enum=backend.settings.GridVerticalContainerSpacing, max_length=255, verbose_name='Vertical internal spacing'),
        ),
        migrations.AlterField(
            model_name='bootstrap4gridcontainer',
            name='width',
            field=enumfields.fields.EnumField(default='full-width', enum=backend.settings.GridContainerWidthInternal, max_length=255, verbose_name='Width'),
        ),
    ]
