# Generated by Django 4.2.4 on 2023-08-20 15:56

from django.db import migrations, models
import django.db.models.deletion
import djangocms_bootstrap4.contrib.bootstrap4_grid.constants
import enumfields.fields


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0022_auto_20180620_1551"),
        ("bootstrap4_grid", "0018_auto_20210719_2034"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bootstrap4gridcolumn",
            name="cmsplugin_ptr",
            field=models.OneToOneField(
                auto_created=True,
                on_delete=django.db.models.deletion.CASCADE,
                parent_link=True,
                primary_key=True,
                related_name="%(app_label)s_%(class)s",
                serialize=False,
                to="cms.cmsplugin",
            ),
        ),
        migrations.AlterField(
            model_name="bootstrap4gridcontainer",
            name="cmsplugin_ptr",
            field=models.OneToOneField(
                auto_created=True,
                on_delete=django.db.models.deletion.CASCADE,
                parent_link=True,
                primary_key=True,
                related_name="%(app_label)s_%(class)s",
                serialize=False,
                to="cms.cmsplugin",
            ),
        ),
        migrations.AlterField(
            model_name="bootstrap4gridcontainer",
            name="container_type",
            field=enumfields.fields.EnumField(
                default="container-fluid",
                enum=djangocms_bootstrap4.contrib.bootstrap4_grid.constants.GridContainerType,
                max_length=255,
                verbose_name="External width",
            ),
        ),
        migrations.AlterField(
            model_name="bootstrap4gridcontainer",
            name="spacing_vertical_external",
            field=enumfields.fields.EnumField(
                default="none",
                enum=djangocms_bootstrap4.contrib.bootstrap4_grid.constants.GridContainerVerticalSpacingInternal,
                max_length=255,
                verbose_name="Vertical external spacing",
            ),
        ),
        migrations.AlterField(
            model_name="bootstrap4gridcontainer",
            name="spacing_vertical_internal",
            field=enumfields.fields.EnumField(
                default="none",
                enum=djangocms_bootstrap4.contrib.bootstrap4_grid.constants.GridContainerVerticalSpacingInternal,
                max_length=255,
                verbose_name="Vertical internal spacing",
            ),
        ),
        migrations.AlterField(
            model_name="bootstrap4gridcontainer",
            name="width",
            field=enumfields.fields.EnumField(
                default="full-width",
                enum=djangocms_bootstrap4.contrib.bootstrap4_grid.constants.GridContainerWidthInternal,
                max_length=255,
                verbose_name="Width",
            ),
        ),
        migrations.AlterField(
            model_name="bootstrap4gridrow",
            name="cmsplugin_ptr",
            field=models.OneToOneField(
                auto_created=True,
                on_delete=django.db.models.deletion.CASCADE,
                parent_link=True,
                primary_key=True,
                related_name="%(app_label)s_%(class)s",
                serialize=False,
                to="cms.cmsplugin",
            ),
        ),
    ]
