repos:
  -  repo: https://github.com/asottile/pyupgrade
     rev: v2.29.0
     hooks:
       -  id: pyupgrade
          args: ["--py37-plus"]

  - repo: https://github.com/PyCQA/flake8
    rev: 3.9.2
    hooks:
      - id: flake8
        additional_dependencies:
          - flake8-broken-line
          - flake8-bugbear
          - flake8-builtins
          - flake8-comprehensions
          - flake8-eradicate
          - flake8-tidy-imports
          - pep8-naming
