# Generated by Django 1.11.11 on 2018-06-10 11:06
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bootstrap5_tabs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bootstrap5tab',
            old_name='tab_style',
            new_name='template',
        ),
    ]
