# Generated by Django 1.9.13 on 2017-10-15 20:51
import django.db.models.deletion
from django.db import migrations, models

import djangocms_bootstrap5.fields
from djangocms_bootstrap5.constants import TAG_CHOICES


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cms', '0016_auto_20160608_1535'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bootstrap5Jumbotron',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='bootstrap5_jumbotron_bootstrap5jumbotron', serialize=False, to='cms.CMSPlugin')),
                ('fluid', models.BooleanField(default=False, help_text='Adds the .jumbotron-fluid class.', verbose_name='Fluid')),
                ('tag_type', djangocms_bootstrap5.fields.TagTypeField(choices=TAG_CHOICES, default=TAG_CHOICES[0][0], help_text='Select the HTML tag to be used.', max_length=255, verbose_name='Tag type')),
                ('attributes', djangocms_bootstrap5.fields.AttributesField(blank=True, default=dict, verbose_name='Attributes')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
    ]
