# Generated by Django 2.2.12 on 2020-05-03 11:47

from django.db import migrations, models
import django.db.models.deletion
import djangocms_bootstrap4.contrib.bootstrap4_heading.constants
import djangocms_bootstrap4.fields
import enumfields.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bootstrap4Heading',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='bootstrap4_heading_bootstrap4heading', serialize=False, to='cms.CMSPlugin')),
                ('text', models.TextField(max_length=2048)),
                ('tag', enumfields.fields.EnumField(default='h1', enum=djangocms_bootstrap4.contrib.bootstrap4_heading.constants.HeadingTag, max_length=32)),
                ('alignment', enumfields.fields.EnumField(default='left', enum=djangocms_bootstrap4.contrib.bootstrap4_heading.constants.HeadingAlignment, max_length=32)),
                ('size', models.FloatField(blank=True, help_text='Optional', null=True)),
                ('size_unit', enumfields.fields.EnumField(default='px', enum=djangocms_bootstrap4.contrib.bootstrap4_heading.constants.SizeUnit, max_length=32)),
                ('type', enumfields.fields.EnumField(blank=True, default='normal', enum=djangocms_bootstrap4.contrib.bootstrap4_heading.constants.HeadingType, max_length=32, null=True)),
                ('color', enumfields.fields.EnumField(default='dark', enum=djangocms_bootstrap4.contrib.bootstrap4_heading.constants.HeadingColor, max_length=32)),
                ('attributes', djangocms_bootstrap4.fields.AttributesField(blank=True, default=dict, verbose_name='Attributes')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
    ]
