# Generated by Django 3.1.4 on 2021-07-19 18:34

import backend.settings
from django.db import migrations
import enumfields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('bootstrap4_heading', '0002_rename_field_text_to_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bootstrap4heading',
            name='color',
            field=enumfields.fields.EnumField(default='dark', enum=backend.settings.HeadingColor, max_length=32),
        ),
        migrations.AlterField(
            model_name='bootstrap4heading',
            name='type',
            field=enumfields.fields.EnumField(blank=True, default='normal', enum=backend.settings.HeadingType, max_length=32, null=True),
        ),
    ]
