name: Publish Python 🐍 distributions 📦 to TestPyPI

on:
  push:
    branches:
      - master

jobs:
  build-n-publish:
    name: TestPyPI - Build and publish Python 🐍 distributions 📦
    runs-on: ubuntu-latest
    environment:
      name: test
      url: https://test.pypi.org/p/djangocms-bootstrap4
    permissions:
      id-token: write
    steps:
    - uses: actions/checkout@master
    - name: Set up Python 3.9
      uses: actions/setup-python@v1
      with:
        python-version: 3.9

    - name: Install pypa/build
      run: >-
        python -m
        pip install
        build
        --user
    - name: Build a binary wheel and a source tarball
      run: >-
        python -m
        build
        --sdist
        --wheel
        --outdir dist/
        .

    - name: Publish distribution 📦 to Test PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        repository_url: https://test.pypi.org/legacy/
        skip_existing: true
