# Generated by Django 3.1.4 on 2021-01-07 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bootstrap4_content', '0002_added_figure'),
    ]

    operations = [
        migrations.AddField(
            model_name='bootstrap4blockquote',
            name='quote_origin_subtext',
            field=models.CharField(blank=True, max_length=256, verbose_name='Cite subtext'),
        ),
    ]
